// Add fake data constants
export const DEFAULT_COURSES = [
  {
    id: "c1",
    name: "Structured and Object-Oriented Programming",
    code: "BCSE101P",
    credits: 2,
  },
  { id: "c2", name: "Differential Equations", code: "BMAT102P", credits: 4 },
  { id: "c3", name: "Engineering Physics", code: "BPHY101P", credits: 2 },
  { id: "c4", name: "Quantitative Skills", code: "BSTS101P", credits: 1 },
  {
    id: "c5",
    name: "Technical English Communication",
    code: "BENG101P",
    credits: 2,
  },
  { id: "c6", name: "Web Development", code: "BCSE102P", credits: 3 },
  {
    id: "c7",
    name: "Structured and Object-Oriented Programming Lab",
    code: "BCSE101L",
    credits: 2,
  },
  { id: "c8", name: "Engineering Physics Lab", code: "BPHY101L", credits: 1 },
  {
    id: "c9",
    name: "Technical English Communication Lab",
    code: "BENG101L",
    credits: 1,
  },
];

export const DEFAULT_TEACHERS = [
  {
    id: "t1",
    name: "Vinila Jinny",
    color: "cyan",
    slots: ["B2"],
    venue: "PRP 105",
    course: "c1",
  },
  {
    id: "t2",
    name: "Vinila Jinny",
    color: "cyan",
    slots: ["L5", "L6", "L27", "L28"],
    venue: "PRP 118",
    course: "c7",
  },
  {
    id: "t3",
    name: "MurugusundaraMoorthy",
    color: "fuchsia",
    slots: ["C2", "TC2", "TCC2"],
    venue: "PRP 109",
    course: "c2",
  },
  {
    id: "t4",
    name: "Samuel P",
    color: "indigo",
    slots: ["E2", "TE2"],
    venue: "PRP 116",
    course: "c3",
  },
  {
    id: "t5",
    name: "Samuel P",
    color: "indigo",
    slots: ["L3", "L4"],
    venue: "PRP 116",
    course: "c8",
  },
  {
    id: "t6",
    name: "Sakshi",
    color: "lime",
    slots: ["F2", "TF2"],
    venue: "PRP 116",
    course: "c4",
  },
  {
    id: "t7",
    name: "Mary Jennifier",
    color: "orange",
    slots: ["G2"],
    venue: "PRP 127",
    course: "c5",
  },
  {
    id: "t8",
    name: "Mary Jennifier",
    color: "orange",
    slots: ["L29", "L30"],
    venue: "PRP 127",
    course: "c9",
  },
  {
    id: "t9",
    name: "Justin Gopinath",
    color: "pink",
    slots: ["L23", "L24", "L25", "L26", "TG2"],
    venue: "PRP 236",
    course: "c6",
  },
  {
    id: "t10",
    name: "Jitendra Behera",
    color: "purple",
    slots: ["E2", "TE2"],
    venue: "PRP 116",
    course: "c3",
  },
  {
    id: "t11",
    name: "Jitendra Behera",
    color: "purple",
    slots: ["L3", "L4"],
    venue: "PRP 116",
    course: "c8",
  },
  {
    id: "t12",
    name: "John Doe",
    color: "teal",
    slots: ["G2"],
    venue: "PRP 127",
    course: "c2",
  },
];